version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - "memextech/maintainers"
    assignees:
      - "memextech/maintainers"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "memextech/maintainers"
    assignees:
      - "memextech/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Git submodule (ht-core) - if supported in future
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 2
    reviewers:
      - "memextech/maintainers"
    assignees:
      - "memextech/maintainers"
    labels:
      - "dependencies"
      - "submodule"
    commit-message:
      prefix: "deps"
      include: "scope"